_format_version: "1.1"

services:
- connect_timeout: 60000
  host: my-api
  name: service_products
  path: /api/products
  port: 8084
  protocol: http
  routes:
  - name: route_products
    methods:
    - GET
    - POST
    - PUT
    paths:
    - /api/products
    protocols:
    - http
    - https
    strip_path: true

